# Generated by Django 4.2 on 2023-04-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('status', models.CharField(choices=[('not started', 'not started'), ('in progress', 'in progress'), ('completed', 'completed')], max_length=50, verbose_name='Status')),
                ('priority', models.CharField(choices=[('medium', 'medium'), ('high', 'high'), ('low', 'low')], max_length=20, verbose_name='Priority')),
            ],
        ),
    ]
