# Generated by Django 4.2 on 2023-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_date_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='genec',
            field=models.CharField(choices=[('completed', 'completed'), ('not started', 'not started'), ('in progress', 'in progress')], default=1, max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
